project_name: kubectl-pdebug
builds:
  - id: kubectl-pdebug
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"

archives:
  - format: binary

checksum:
  name_template: sha256_checksums.txt
  algorithm: sha256
  ids:
    - kubectl-pdebug